# install:
#   # Install conda
#   - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#   - bash miniconda.sh -b -p $HOME/miniconda
#   - source "$HOME/miniconda/etc/profile.d/conda.sh"
#   - hash -r
#   - conda config --set always_yes yes --set changeps1 no
#   - conda update -q conda
#   - conda info -a
#   # Install poetry
#   - pip install poetry
# script:
#   # CI
#   - make env
#   - conda activate django-on-aws
#   - make test
#   # CD
#   - make build
#   - make package
#   - make start-api &
#   - make test-local-api
#   - make deploy
#   - make check-api-is-secured
#   - make check-healthcheck-endpoint