dockerhub_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38653438393439653936393436303932613063613537663964316333623533386132393739303462
          3437663562636135333133333237353230303663313234340a616632313336623161393464336362
          32323562386665373034656466366338333263633365323134653862313361333137346234316334
          3130656435323262610a646464316663643635373838653033343538633764383437653336323936
          6431
